#! /bin/bash
myapp=myapp
myname=$(echo $0 | sed 's|.*/||')
mydir=$(dirname $0)/

function usage() {
    cat <<- xxx
	Usage: $myname [+h] [+v] [+noop] <application-args>

	Runs the $myapp application.

	+h - print this message and stop. To see the application's
	     help message use '-h'.
	+v - print the java command before invocation.
	+noop - don't actually invoke the java command.

	These environment variables are used to alter behavior:
	JAVA - identifies the java command
	MYAPPJAR - identifies the jar file
	xxx
    exit
}

[ -z "$JAVA" ] &&  JAVA=$(which java)

# The jarfile's name and location might be different during development and after installation;
# this script should work unaltered either way.
function findJarFile() for c in ./$myapp*.jar $mydir/$myapp*.jar target/$myapp-*-with-dependencies.jar; do
                         [ -r $c ] && echo $c
                       done
[ -z "$MYAPPJAR" ] && MYAPPJAR=$(findJarFile)

verbose=
noop=
while [ -n "$1" ]; do
  case "$1" in
    +h) usage
	;;
    +v) verbose=verbose
	;;
    +noop) noop=noop
	;;
    *)  break
	;;
  esac
  shift
done

if [ ! -r $MYAPPJAR ]; then
  echo "Couldn't find the jar file!"
  usage
fi

cmd="$JAVA -jar $MYAPPJAR $*"
[ -z "$verbose" ] || echo $cmd
[ -z "$noop" ] && exec $cmd
