#! /bin/bash
myapp=myapp
myname=$(echo $0 | sed 's|.*/||')
mydir=$(dirname $0 | sed 's|/$||')

function usage() {
    cat <<- xxx
	Usage: $myname [+h] [+v] [+noop] <application-args>

	Runs the $myapp application.

	+h - print this message and stop. To see the application's
	     help message use '-h'.
	+v - print the java command before invocation.
	+noop - don't actually invoke the java command.
        +jar - print the path to the jar file and exit.

	These environment variables are used to alter behavior:
	JAVA - identifies the java command
	MYAPPJAR - identifies the jar file
	xxx
    exit
}

[ -z "$JAVA" ] &&  JAVA=$(which java)

# The jarfile's name and location might be different during development and after installation;
# this script should work unaltered either way.
function findJarFile() for c in ./$myapp*.jar ../maven-build-artifacts/$myapp/$myapp-*-with-dependencies.jar \
                                target/$myapp-*-with-dependencies.jar $mydir/$myapp*.jar; do
                         [ -r $c ] && echo $c && return
                       done
[ -z "$MYAPPJAR" ] && MYAPPJAR=$(findJarFile || echo "did-not-find-the-jar-file")

verbose=
noop=
while [ -n "$1" ]; do
  case "$1" in
    +h) usage
	;;
    +v) verbose=verbose
	;;
    +noop) noop=noop; verbose=noop
	;;
    +jar)
	echo $MYAPPJAR
	exit 0
	;;
    *)  break
	;;
  esac
  shift
done

if [ ! -r "$MYAPPJAR" ]; then
  echo "Couldn't find the jar file!"
  usage
fi

# Gotta do tricks to handle command line args that contain space chars.
cmd="$JAVA -jar $MYAPPJAR"
for x in "$@"; do cmd+=" \"$x\""; done

[ -z "$verbose" ] || echo $cmd
[ -z "$noop" ] && eval $cmd
